# 推奨される更新版config
model:
  name_or_path: "google/gemma-2-9b"
  tokenizer_name: null
  cache_dir: null

dataset:
  load_from: "huggingface"
  name: "DeL-TaiseiOzaki/Tengentoppa-sft-v1.0"
  data_files:
    train: "data/dataset_train.json"
  cache_dir: null
  batch_size: 1000  # データ処理用のバッチサイズ
  processing:
    num_proc: 2    # 並列処理数
    cache_enabled: true

training:
  output_dir: "./output/sft_01"
  num_train_epochs: 1
  per_device_train_batch_size: 8 
  block_size: 512
  learning_rate: 1e-5
  seed: 42
  fp16: false
  bf16: true
  optim: "adamw_torch"
  gradient_checkpointing: false
  ddp: false

lora:
  use_lora: True
  use_qlora: false
  r: 32
  alpha: 32
  dropout: 0.1
  target_modules: ["q_proj", "v_proj"]

prompts:
  use_custom_prompt: true
  use_chat_template: true
  default_system_prompt: "あなたは誠実で優秀な日本人のアシスタントです。タスクを説明する指示と、さらなる文脈を提供する入力を元に、要求を適切に完了する応答を書きなさい。\n"
  user_prompt: ""
  template:
    # Gemma用のカスタムテンプレート
    custom_template: |
      <bos><start_of_turn>user
      {%- for message in messages %}
      {%- if message['role'] == 'user' %}
      {{message['content']}}{%- elif message['role'] == 'assistant' %}
      <end_of_turn>
      <start_of_turn>model
      {{message['content']}}{%- elif message['role'] == 'system' %}
      {{message['content']}}{%- endif %}
      {%- endfor %}
      <end_of_turn>
      <start_of_turn>model
    # フォールバック用のテンプレート
    fallback_template: |
      <start_of_turn>system
      {system_content}<end_of_turn>
      <start_of_turn>user
      {user_content}<end_of_turn>
      <start_of_turn>assistant
      {assistant_content}<end_of_turn>
    # アシスタント応答の検出用マーカー
    assistant_markers:
      - "<start_of_turn>model"
      - "<start_of_turn>assistant"
      - "[アシスタント]"
    # メッセージフォーマット設定
    format:
      system_prefix: "<s>[システム]\n"
      user_prefix: "[ユーザー]\n"
      assistant_prefix: "[アシスタント]\n"
      system_suffix: "\n"
      user_suffix: "\n"
      assistant_suffix: "</s>\n"
      instruction_prefix: "###指示\n"
      input_prefix: "\n\n###入力\n"

logging:
  logging_dir: "./logs"
  logging_steps: 500
  use_wandb: true